// Generated by uniffi-bindgen-react-native
#include "mopro-ffi.h"
#include "generated/zksurvey.hpp"

namespace moproffi {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeZksurvey::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}